server:
  port: 8083
  name: huwei
    #  tomcat:
  #api访问日志记录到文档
#    accesslog:
#      enabled: true
#      directory: E:/logs
spring:
  mvc:
    view:
      prefix: /
      suffix: jsp
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:com/wei/mapper/*.xml
  type-aliases-package: classpath:com.wei.bo

  #log4j打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
my:
  name: Awake-HU


